name: Test build 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  controller:
    runs-on: ubuntu-latest

    steps:
#      - name: Preparing controller 
#        run: |
#          sudo apt-get update
#          sudo cargo install sccache
      
      - name: Installing cacche
        run: |
          pushd /tmp
          git clone https://github.com/pietern/ccache -b ccbin
          pushd ccache
          ./autogen.sh
          ./configure --prefix=/usr/local
          sudo make "-j$(nproc)" install
          popd
          popd
          
      - name: Installing scacche
        run: |
          pushd /tmp
          curl -LOs https://github.com/mozilla/sccache/releases/download/0.2.13/sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
          tar -zxvf sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
          sudo mv sccache-0.2.13-x86_64-unknown-linux-musl/sccache /usr/local/bin/sccache
          rm -rf sccache-0.2.13-x86_64-unknown-linux-musl*
          popd

      - name: Creating file
        run: echo "int main () { return 0; }" > foo.c
      
      - name: Testing sccache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_KEY }}
          SCCACHE_ENDPOINT: s3.wasabisys.com:443
          SCCACHE_BUCKET: kiwibrowser
          SCCACHE_S3_USE_SSL: true
          SCCACHE_LOG_LEVEL: trace
          SCCACHE_NO_DAEMON: 1
          RUST_BACKTRACE: 1
          SCCACHE_START_SERVER: 1
        run: sccache gcc -o foo.o -c foo.c
        
      - name: Listing files
        run: ls -la

      - name: Listing files
        run: ls -la /tmp
        
      - name: Listing files
        run: ls -la /tmp/ccache
