name: Test build 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  controller:
    runs-on: ubuntu-latest

    steps:
      - name: Preparing controller 
        run: |
          sudo apt-get update
          sudo apt-get install scacche
      
