name: Test build 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  controller:
    runs-on: ubuntu-latest

    steps:
      - name: Preparing controller 
        run: ifconfig -a
      
      - name: Getting external IP
        run: curl ipinfo.io
      
      - name: Downloading file
        env:
          WASABI_FTP_USERNAME: ${{ secrets.WASABI_FTP_USERNAME }}
          WASABI_FTP_PASSWORD: ${{ secrets.WASABI_FTP_PASSWORD }}
        run: wget ftp://$WASABI_FTP_USERNAME:$WASABI_FTP_PASSWORD@s3.wasabisys.com/kiwibrowser/32768.rnd
      
      
