name: Test build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  controller:
    runs-on: ubuntu-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    # /dev/sda1 has more available space than /dev/sdb1 (14 GB only on /dev/sdb1 at this stage)
    # so we want to take advantage of the available disk space on /dev/sda1
      
    # We store the main repository on /dev/sda1
    # We store the dependencies and output objects on /dev/sdb1 
    steps:
      - name: Initializing build
        run: echo Initializing build for platform arm

      - name: Install
        run: sudo apt-get install -y rclone

      - name: Creating rclone config
        run: |
          mkdir -p /home/runner/.config/rclone/
          echo '[cache]' > /home/runner/.config/rclone/rclone.conf
          echo 'endpoint = s3.wasabisys.com' >> /home/runner/.config/rclone/rclone.conf

      - name: Pushing
        run: rclone ls cache:kiwibrowser-arm
