name: Test build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  controller:
    runs-on: ubuntu-latest

    steps:
      - name: Preparing controller
        run: ifconfig -a
      
      - name: Installing distcc
        run: sudo apt-get install -y distcc

      - name: Installing ZeroTier (networking)
        run: curl -s https://install.zerotier.com | sudo bash
      
      - name: Joining network
        run: sudo zerotier-cli join 17d709436cfef35a
        
      - name: Preparing controller
        run: ifconfig -a
        
      - name: Listing peers
        run: sudo zerotier-cli listpeers

  slave:
    runs-on: ubuntu-latest

    steps:
      - name: Preparing slave
        run: ifconfig -a

      - name: Installing ZeroTier (networking)
        run: curl -s https://install.zerotier.com | sudo bash
        
      - name: Joining network
        run: sudo zerotier-cli join 17d709436cfef35a
        
      - name: Preparing controller
        run: ifconfig -a

      - name: Listing peers
        run: sudo zerotier-cli listpeers
